### ISSUE TITLE
Proposals page is included in the stable release of the spec, featuring old proposal listings

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-spec#1029]
The following historical copies of the spec proposals page are currently publicly available:

* https://spec.matrix.org/v1.1/proposals/
* https://spec.matrix.org/v1.2/proposals/

These contain old copies of the proposal listings, with the latter (v1.2) being what users navigate to by default when visiting https://spec.matrix.org and clicking "Spec Change Proposals" in the left sidebar.

Ideally there should only ever be an up-to-date copy of the page available ([/unstable/proposals](https://spec.matrix.org/unstable/proposals)), which users should be directed to when they try to visit any versioned copies of the page. The easiest way to do this as @turt2live proposes is to simply redirect the above listed pages to `/unstable/proposals`.

Bonus points (but please this as well) if while we're messing about with reverse proxy configs if we can instead host the page on `spec.matrix.org/proposals`, as I find that cleaner than `/unstable/proposals`, and makes sense as the page is not intended to be versioned.

**Comment by turt2live** [comment]
I'd advocate we make the bonus points the actual actionable piece of this :)

**Comment by richvdh** [comment]
This got fixed via matrix-org/matrix-ansible-private#5394

**Comment by turt2live** [comment]
arguably not fixed as the build still contains them, but for deployment purposes this is fine?

**Comment by richvdh** [comment]
related: #1367
