### ISSUE TITLE
Set a published date on static spec builds to fix search engines

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#728]
They seem to love promoting old versions of the spec, which is less than helpful

**Comment by turt2live** [comment]
Counting as fixed with the new spec site

**Comment by aaronraimist** [comment]
@turt2live did you confirm https://github.com/matrix-org/matrix-spec/issues/728#issuecomment-1055972691 still exists? I don't see it anymore but maybe I'm just missing it.

I see it on a draft version from the site around the time of that comment https://friendly-yonath-3de225.netlify.app but not on the current site <img width="1342" src="https://user-images.githubusercontent.com/5855073/170808527-16ec2db8-73bf-4bb5-a7e8-bc9992385aac.png">

**Comment by turt2live** [comment]
I did a few searches and Google at least appears to have figured it out - it usually points to `/latest` and sometimes `/unstable`, which is better than r0.2 in some cases.
